### PR TITLE
Add failure labels

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
Allows adding backport failure labels to the original PR.

For example, adding ...
```
failure_labels: "failed backport"
```
... to the workflow would add a "failed backport" label to a PR that had a failed backport.

Also,
* Regenerated the lockfile
* Refactored the utilis
* Bumped the version
 
### Check List
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by peternied — APPROVED** [review]
I like this - it allows for discovering failures associated with the issue and then lets the repo update the pull request indicating the issue has been resolved.

**Review by VachaShah — APPROVED** [review]
This looks great! Can you also add it to the README in the [features](https://github.com/VachaShah/backport#features) section?

**Comment by AMoo-Miki** [comment]
> This looks great! Can you also add it to the README in the [features](https://github.com/VachaShah/backport#features) section?

Thanks. Features updated.

**Comment by VachaShah** [comment]
> > This looks great! Can you also add it to the README in the [features](https://github.com/VachaShah/backport#features) section?
> 
> Thanks. Features updated.

Thanks @AMoo-Miki! I just pushed some changes to fix the prettier and lint errors, can you take those latest changes from main?

**Review by VachaShah — APPROVED** [review]

**Comment by peternied** [comment]
@VachaShah Has this change rolled out? How can we see it in https://github.com/opensearch-project/security?

**Comment by VachaShah** [comment]
> @VachaShah Has this change rolled out? How can we see it in https://github.com/opensearch-project/security?

Hi @peternied it has! You can use it from version 2.2.0.

**Pull request merged**
